### ISSUE TITLE
Google Scholar link

### ISSUE THREAD

**Issue by sjackman** [bcgsc/btl#10]
On my page http://www.birollab.ca/member/sjackman
clicking on the Google Scholar icon goes to http://www.birollab.ca/assets/gschol-icon.png
rather than the desired profile page.

**Comment by gejessicama** [comment]
f8da8c62481111b4a965bcea0f508d4558261f97

Whoops. There was a typo in the profile layout. gchsol -> gschol

**Comment by sjackman** [comment]
Thanks for the fix!
