### ISSUE TITLE
Copyright statement

### ISSUE THREAD

**Issue by sjackman** [bcgsc/btl#5]
Since Bioinformatics Technology Lab is not incorporated, it cannot hold a copyright. Please change `© Bioinformatics Technology Lab 2018` to `Copyright 2018 BC Cancer Genome Sciences Centre`. Please use Copyright rather than ©.

**Comment by gejessicama** [comment]
https://github.com/bcgsc/btl/commit/ae80d7a2b7feb8fc5b7b9f3a810523772d1ab94d

Done!
